# Generated by Django 5.1.5 on 2025-02-18 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_customuser_is_director_customuser_is_teacher_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classroom',
            new_name='Classe',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='classroom',
            new_name='classe',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='classroom',
            new_name='classe',
        ),
    ]
