# Generated by Django 5.1.6 on 2025-03-05 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_classe_school_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='period',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='base.subject'),
            preserve_default=False,
        ),
    ]
